import AppKit
import UniformTypeIdentifiers

/// Surveille le presse-papier du Mac. macOS n'envoie pas de notification : on compare
/// `changeCount` à intervalle régulier, ce qui ne coûte presque rien.
public final class ClipboardWatcher {
    public var onContent: ((ClipContent) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChange: Int
    private var timer: Timer?

    /// Types posés par les gestionnaires de mots de passe (convention nspasteboard.org) :
    /// ces contenus ne quittent jamais le Mac.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    public init() {
        lastChange = pasteboard.changeCount
    }

    public func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in self?.tick() }
        timer?.tolerance = 0.2
    }

    /// Écrit un contenu reçu sans qu'il soit renvoyé à l'expéditeur.
    public func write(_ content: ClipContent) {
        pasteboard.clearContents()
        switch content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data, _):
            // PNG + TIFF : la plupart des apps Mac lisent l'un ou l'autre.
            if let rep = NSBitmapImageRep(data: data) {
                let item = NSPasteboardItem()
                if let png = rep.representation(using: .png, properties: [:]) { item.setData(png, forType: .png) }
                if let tiff = rep.tiffRepresentation { item.setData(tiff, forType: .tiff) }
                pasteboard.writeObjects([item])
            }
        }
        lastChange = pasteboard.changeCount
    }

    /// Contenu actuel du presse-papier, s'il peut être partagé.
    public func currentShareable() -> ClipContent? {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Self.privateTypes) { return nil }

        // Fichier copié dans le Finder : on n'envoie que les images (le nom seul ne sert à rien).
        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
            return imageFile()
        }

        // Image (capture d'écran, « Copier l'image »)… sauf texte mis en forme contenant des images,
        // où c'est le texte qui compte.
        let richText = types.contains(NSPasteboard.PasteboardType.rtf.rawValue)
            || types.contains(NSPasteboard.PasteboardType.rtfd.rawValue)
        if !richText {
            if let png = pasteboard.data(forType: .png) { return ImageCodec.prepare(png, mime: "image/png") }
            if let tiff = pasteboard.data(forType: .tiff) { return ImageCodec.prepare(tiff, mime: "image/tiff") }
        }

        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return nil }
        return .text(text)
    }

    private func imageFile() -> ClipContent? {
        let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                          options: [.urlReadingFileURLsOnly: true]) as? [URL] ?? []
        guard urls.count == 1, let url = urls.first,
              let type = UTType(filenameExtension: url.pathExtension), type.conforms(to: .image),
              let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize, size <= 50 * 1024 * 1024,
              let data = try? Data(contentsOf: url) else { return nil }
        return ImageCodec.prepare(data, mime: type.preferredMIMEType ?? "image/octet-stream")
    }

    private func tick() {
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        if let content = currentShareable() { onContent?(content) }
    }
}
